# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef69ddc1a1c79f1ff2ddf6429c717fccd2073b86de370ac2fb0b52ec4eb9351502bff27d305055498b8387f03254f03ee2f16f419e69a14867102df53e6f067

test:
  secret_key_base: 5f402dbaf5ae0dd8b24a893db19ae1531d040de81b0a229f2ea4feb9bfc74d44e44d7af2f6a971a6b8ff55b08122b29a216c8b4e63950e084875c5d34afd6b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
